In [1]:
#!pip install onnx

In [2]:
#paquetes
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import helper
import matplotlib.pyplot as plt

import numpy as np
import torch
from torchvision import datasets,transforms

In [3]:
import pandas as pd

In [4]:
#preparacion de datos
df= pd.read_csv('/content/sensor_readings_24.csv', header=None)

In [5]:
df

0      1      2      3      4      5      6      7      8      9   \
0     0.438  0.498  3.625  3.645  5.000  2.918  5.000  2.351  2.332  2.643   
1     0.438  0.498  3.625  3.648  5.000  2.918  5.000  2.637  2.332  2.649   
2     0.438  0.498  3.625  3.629  5.000  2.918  5.000  2.637  2.334  2.643   
3     0.437  0.501  3.625  3.626  5.000  2.918  5.000  2.353  2.334  2.642   
4     0.438  0.498  3.626  3.629  5.000  2.918  5.000  2.640  2.334  2.639   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5451  0.910  5.000  3.997  2.785  2.770  2.572  2.433  1.087  1.772  1.040   
5452  0.926  5.000  4.015  2.792  2.777  2.571  1.768  1.071  1.762  1.021   
5453  0.937  5.000  4.034  2.799  2.784  2.571  1.754  1.053  1.752  1.002   
5454  0.945  4.052  4.052  2.809  2.791  2.441  1.757  1.034  1.743  0.983   
5455  0.950  4.066  5.000  2.819  2.798  2.570  2.422  1.016  1.739  0.964   

      ...     15     16     17     18     19     20     21     22     23  \
0     ...  0.593  0.502  0.493  0.504  0.445  0.431  0.444  0.440  0.429   
1     ...  0.592  0.502  0.493  0.504  0.449  0.431  0.444  0.443  0.429   
2     ...  0.593  0.502  0.493  0.504  0.449  0.431  0.444  0.446  0.429   
3     ...  0.593  0.502  0.493  0.504  0.449  0.431  0.444  0.444  0.429   
4     ...  0.592  0.502  0.493  0.504  0.449  0.431  0.444  0.441  0.429   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5451  ...  0.660  0.648  0.657  0.686  5.000  1.045  5.000  5.000  1.562   
5452  ...  0.652  0.640  0.649  1.593  1.616  1.058  5.000  5.000  1.085   
5453  ...  0.648  0.633  0.642  0.741  5.000  1.065  5.000  5.000  1.105   
5454  ...  0.641  0.626  0.635  0.754  5.000  1.076  5.000  5.000  1.118   
5455  ...  0.635  0.618  0.628  0.776  5.000  1.083  5.000  5.000  1.168   

                     24  
0     Slight-Right-Turn  
1     Slight-Right-Turn  
2     Slight-Right-Turn  
3     Slight-Right-Turn  
4     Slight-Right-Turn  
...                 ...  
5451       Move-Forward  
5452   Sharp-Right-Turn  
5453   Sharp-Right-Turn  
5454       Move-Forward  
5455   Sharp-Right-Turn  

[5456 rows x 25 columns]

In [6]:
df[24] = pd.Categorical(df[24]).codes

In [7]:
df

0      1      2      3      4      5      6      7      8      9   \
0     0.438  0.498  3.625  3.645  5.000  2.918  5.000  2.351  2.332  2.643   
1     0.438  0.498  3.625  3.648  5.000  2.918  5.000  2.637  2.332  2.649   
2     0.438  0.498  3.625  3.629  5.000  2.918  5.000  2.637  2.334  2.643   
3     0.437  0.501  3.625  3.626  5.000  2.918  5.000  2.353  2.334  2.642   
4     0.438  0.498  3.626  3.629  5.000  2.918  5.000  2.640  2.334  2.639   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5451  0.910  5.000  3.997  2.785  2.770  2.572  2.433  1.087  1.772  1.040   
5452  0.926  5.000  4.015  2.792  2.777  2.571  1.768  1.071  1.762  1.021   
5453  0.937  5.000  4.034  2.799  2.784  2.571  1.754  1.053  1.752  1.002   
5454  0.945  4.052  4.052  2.809  2.791  2.441  1.757  1.034  1.743  0.983   
5455  0.950  4.066  5.000  2.819  2.798  2.570  2.422  1.016  1.739  0.964   

      ...     15     16     17     18     19     20     21     22     23  24  
0     ...  0.593  0.502  0.493  0.504  0.445  0.431  0.444  0.440  0.429   3  
1     ...  0.592  0.502  0.493  0.504  0.449  0.431  0.444  0.443  0.429   3  
2     ...  0.593  0.502  0.493  0.504  0.449  0.431  0.444  0.446  0.429   3  
3     ...  0.593  0.502  0.493  0.504  0.449  0.431  0.444  0.444  0.429   3  
4     ...  0.592  0.502  0.493  0.504  0.449  0.431  0.444  0.441  0.429   3  
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ..  
5451  ...  0.660  0.648  0.657  0.686  5.000  1.045  5.000  5.000  1.562   0  
5452  ...  0.652  0.640  0.649  1.593  1.616  1.058  5.000  5.000  1.085   1  
5453  ...  0.648  0.633  0.642  0.741  5.000  1.065  5.000  5.000  1.105   1  
5454  ...  0.641  0.626  0.635  0.754  5.000  1.076  5.000  5.000  1.118   0  
5455  ...  0.635  0.618  0.628  0.776  5.000  1.083  5.000  5.000  1.168   1  

[5456 rows x 25 columns]

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
#para normalizar los datos
scaler = MinMaxScaler()

# Selecciona las columnas que deseas normalizar
columnas_a_normalizar = df.columns  # Puedes seleccionar las columnas que desees



In [10]:
columnas_a_normalizar=columnas_a_normalizar.drop(24)

In [11]:
# Normaliza los datos
df[columnas_a_normalizar] = scaler.fit_transform(df[columnas_a_normalizar])

In [12]:
df[24].nunique()

4

In [13]:
#importamos los modulos necesarios
from torch import nn
import torch.nn.functional as F

In [14]:
#creamos la red
class RedNeuronal(nn.Module):
  def __init__(self):
    super().__init__()
    # definimos metodos lineales
    ## 24 > 20 > 15 > 10 > 5 > 3 softmax
    self.fc1 = nn.Linear(24,20)
    self.fc2 = nn.Linear(20,15)
    self.fc3 = nn.Linear(15,10)
    self.fc4 = nn.Linear(10,5)
    self.fc5 = nn.Linear(5,4)
  def forward(self,x):
    #Funcion que realiza la operacion de pase frontal y obtiene las probabilidades
    x = self.fc1(x)
    x = F.relu(x)
    x = self.fc2(x)
    x = F.relu(x)
    x = self.fc3(x)
    x = F.relu(x)
    x = self.fc4(x)
    x = F.relu(x)
    x = self.fc5(x)
    x = F.softmax(x,dim=1)


    return x


In [15]:
#instanciamos la red
model = RedNeuronal()
print(model)

RedNeuronal(
  (fc1): Linear(in_features=24, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=15, bias=True)
  (fc3): Linear(in_features=15, out_features=10, bias=True)
  (fc4): Linear(in_features=10, out_features=5, bias=True)
  (fc5): Linear(in_features=5, out_features=4, bias=True)
)


In [16]:
#llenamos de 0
model.fc1.bias.data.fill_(0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#inicializamos los pesos con desviacion estandar
model.fc1.weight.data.normal_(std=0.01)

tensor([[ 2.1859e-02, -1.1722e-02,  2.0807e-03,  1.5295e-03, -4.8915e-03,
         -2.1684e-03, -1.1059e-02, -1.5116e-02, -1.3769e-02,  5.5437e-03,
          5.9817e-03, -9.0873e-04,  7.6417e-03, -6.6942e-03, -2.7441e-03,
         -1.0791e-02, -2.8756e-03, -1.0470e-02,  4.4421e-03,  5.1983e-03,
          1.5160e-02,  1.2817e-02, -7.3145e-03,  7.6105e-03],
        [-6.0298e-04,  2.5693e-03, -9.4224e-03, -6.4559e-03,  1.1900e-03,
         -1.2165e-02,  1.0683e-02,  1.2789e-02, -1.2671e-02, -4.5303e-03,
          2.2729e-04, -1.1873e-03,  1.4988e-02, -1.6291e-03,  3.9209e-03,
          9.4990e-03,  1.1003e-02, -1.4267e-03,  3.5845e-02, -9.7617e-03,
         -2.6956e-03, -2.5532e-02,  1.8385e-02,  2.1116e-02],
        [-1.3668e-03,  7.7106e-03, -2.7854e-03,  8.5817e-03, -6.6445e-03,
         -8.2730e-03, -5.3230e-03,  8.4471e-04,  8.9891e-03, -1.5460e-02,
          1.1689e-02, -1.1012e-02, -9.4960e-03, -3.2258e-03, -7.8206e-04,
          4.5860e-03,  9.7663e-03, -1.7133e-02, -1.4864e-02,  

In [18]:
#comvertimos los datos a tensores


# Convierte el DataFrame a un arreglo de NumPy
array = df.values

# Convierte el arreglo de NumPy a un tensor de PyTorch
tensor = torch.tensor(array)

# Muestra el tensor resultante
print(tensor)

tensor([[0.0083, 0.0133, 0.6920,  ..., 0.0158, 0.0112, 3.0000],
        [0.0083, 0.0133, 0.6920,  ..., 0.0164, 0.0112, 3.0000],
        [0.0083, 0.0133, 0.6920,  ..., 0.0171, 0.0112, 3.0000],
        ...,
        [0.1167, 0.9946, 0.7818,  ..., 1.0000, 0.1575, 1.0000],
        [0.1185, 0.7879, 0.7857,  ..., 1.0000, 0.1603, 0.0000],
        [0.1196, 0.7910, 0.9936,  ..., 1.0000, 0.1711, 1.0000]],
       dtype=torch.float64)


In [19]:
#separamos los datos de entrenamiento con los de prueba

train_size = int(0.8 * tensor.size(0))

# Divide el tensor en datos de entrenamiento y datos de prueba
datos_entrenamiento, datos_prueba = torch.split(tensor, [train_size, tensor.size(0) - train_size])

# Muestra los tamaños de los datos de entrenamiento y prueba
print("Tamaño de los datos de entrenamiento:", datos_entrenamiento.size(0))
print("Tamaño de los datos de prueba:", datos_prueba.size(0))

Tamaño de los datos de entrenamiento: 4364
Tamaño de los datos de prueba: 1092


In [20]:
#separamos datos de los resultados(test)
# Obtiene todas las filas y todas las columnas excepto la última (datos de entrada)
datosTest = datos_prueba[:, :-1]

# Obtiene todas las filas y la última columna (resultados)
etiquetasTest = datos_prueba[:, -1]

# Muestra los datos de entrada y los resultados
print("Datos de entrada:")
print(datos_prueba)
print("\nResultados:")
print(etiquetasTest)

Datos de entrada:
tensor([[0.1422, 0.1404, 0.2860,  ..., 0.1420, 0.1438, 0.0000],
        [0.3137, 0.2256, 0.3488,  ..., 0.1459, 0.1518, 0.0000],
        [0.3174, 0.1491, 0.3529,  ..., 0.1498, 0.1529, 0.0000],
        ...,
        [0.1167, 0.9946, 0.7818,  ..., 1.0000, 0.1575, 1.0000],
        [0.1185, 0.7879, 0.7857,  ..., 1.0000, 0.1603, 0.0000],
        [0.1196, 0.7910, 0.9936,  ..., 1.0000, 0.1711, 1.0000]],
       dtype=torch.float64)

Resultados:
tensor([0., 0., 0.,  ..., 1., 0., 1.], dtype=torch.float64)


In [21]:
#separamos datos de los resultados
# Obtiene todas las filas y todas las columnas excepto la última (datos de entrada)
datos_entrada = datos_entrenamiento[:, :-1]

# Obtiene todas las filas y la última columna (resultados)
etiquetas = datos_entrenamiento[:, -1]

# Muestra los datos de entrada y los resultados
print("Datos de entrada:")
print(datos_entrada)
print("\nResultados:")
print(etiquetas)

Datos de entrada:
tensor([[0.0083, 0.0133, 0.6920,  ..., 0.0160, 0.0158, 0.0112],
        [0.0083, 0.0133, 0.6920,  ..., 0.0160, 0.0164, 0.0112],
        [0.0083, 0.0133, 0.6920,  ..., 0.0160, 0.0171, 0.0112],
        ...,
        [0.1311, 0.1286, 0.2788,  ..., 0.1326, 0.1308, 0.1391],
        [0.1348, 0.1330, 0.2794,  ..., 0.1369, 0.1345, 0.1425],
        [0.1378, 0.1360, 0.2810,  ..., 0.1406, 0.1381, 0.1389]],
       dtype=torch.float64)

Resultados:
tensor([3., 3., 3.,  ..., 0., 0., 0.], dtype=torch.float64)


In [22]:
import torch.nn as nn
import torch.optim as optim

In [23]:
import torch.onnx as onnx
from torch.utils.data import DataLoader, Dataset
import torchvision.models as models
import os

# Supongamos que tienes un modelo llamado 'modelo' y quieres guardar checkpoints cada 20 épocas

# Definir el nombre del carpeta donde se guardarán los checkpoints
checkpoint_folder = "checkpoints2/"
# Crear el directorio si no existe
if not os.path.exists(checkpoint_folder):
    os.makedirs(checkpoint_folder)

In [24]:
# Define tu función de pérdida
criterio = nn.CrossEntropyLoss()

# Define tu optimizador
red_neuronal = model
optimizador = optim.Adam(red_neuronal.parameters(), lr=0.001)

# Supongamos que `datos_entrada` y `etiquetas` son tus datos de entrenamiento
for epoch in range(1000):
    # Limpia los gradientes
    optimizador.zero_grad()

    datos_entrada = datos_entrada.to(torch.float)
    # Pase hacia adelante
    resultados = red_neuronal(datos_entrada)

    # Calcula la pérdida
    resultados = resultados.float()

    # Aplica softmax
    resultados_softmax = F.softmax(resultados, dim=1)
    etiquetas = etiquetas.long()
    perdida = criterio(resultados_softmax, etiquetas)

    # Retropropagación
    perdida.backward()

    # Actualiza los pesos
    optimizador.step()

    # Muestra la pérdida
    print('Época [{}/{}], Pérdida: {:.4f}'.format(epoch+1, 1000, perdida.item()))

    # Guardar checkpoint cada 20 épocas
    if (epoch + 1) % 20 == 0:

      checkpoint_path = f"{checkpoint_folder}modelo_epoch_{epoch+1}.pth"
      torch.save({
          'epoch': epoch,
          'model_state_dict': model.state_dict(),
          # Agrega otros elementos que desees guardar
      }, checkpoint_path)

# Convertir el modelo a ONNX
dummy_input = torch.randn(1, 24)  # Input de ejemplo
onnx_path = "modelo.onnx"
torch.onnx.export(model, dummy_input, onnx_path)

Época [1/1000], Pérdida: 1.3901
Época [2/1000], Pérdida: 1.3901
Época [3/1000], Pérdida: 1.3900
Época [4/1000], Pérdida: 1.3899
Época [5/1000], Pérdida: 1.3899
Época [6/1000], Pérdida: 1.3898
Época [7/1000], Pérdida: 1.3898
Época [8/1000], Pérdida: 1.3897
Época [9/1000], Pérdida: 1.3896
Época [10/1000], Pérdida: 1.3896
Época [11/1000], Pérdida: 1.3895
Época [12/1000], Pérdida: 1.3895
Época [13/1000], Pérdida: 1.3894
Época [14/1000], Pérdida: 1.3894
Época [15/1000], Pérdida: 1.3893
Época [16/1000], Pérdida: 1.3893
Época [17/1000], Pérdida: 1.3892
Época [18/1000], Pérdida: 1.3891
Época [19/1000], Pérdida: 1.3891
Época [20/1000], Pérdida: 1.3890
Época [21/1000], Pérdida: 1.3890
Época [22/1000], Pérdida: 1.3889
Época [23/1000], Pérdida: 1.3889
Época [24/1000], Pérdida: 1.3888
Época [25/1000], Pérdida: 1.3888
Época [26/1000], Pérdida: 1.3887
Época [27/1000], Pérdida: 1.3887
Época [28/1000], Pérdida: 1.3886
Época [29/1000], Pérdida: 1.3886
Época [30/1000], Pérdida: 1.3885
Época [31/1000], Pé

In [25]:

# Cambia la red neuronal al modo de evaluación
red_neuronal.eval()

# No necesitamos calcular gradientes durante el test
with torch.no_grad():
    # Pase hacia adelante con los datos de test

    datosTest = datosTest.to(torch.float)
    resultados_test = red_neuronal(datosTest)

    # Calcula las predicciones
    _, predicciones = torch.max(resultados_test, 1)  # Obtiene la clase predicha para cada ejemplo

    # Calcula la precisión
    correctas = (predicciones == etiquetasTest).sum().item()
    total = etiquetasTest.size(0)
    precision = correctas / total
    print('Precisión en el conjunto de test: {:.2f}%'.format(precision * 100))

Precisión en el conjunto de test: 67.22%
